### ISSUE TITLE
doesn't work with javascript-typescript-langserver

### ISSUE THREAD

**Issue by Akuli** [PurpleMyst/sansio-lsp-client#5]
Commands to reproduce:

```
$ git clone https://github.com/PurpleMyst/sansio-lsp-client
$ cd sansio-lsp-client
$ echo console. > playground.js
$ sed -i s/playground.py/playground.js/g sansio_lsp_client/__main__.py
$ sed -i 's/languageId="python"/languageId="javascript"/g' sansio_lsp_client/__main__.py 
$ npm i javascript-typescript-langserver
$ node node_modules/javascript-typescript-langserver/lib/language-server.js
```

Then, in another terminal:

```
$ cd sansio-lsp-client
$ PORT=2089 python3 -m sansio_lsp_client
```

sansio_lsp_client fails with this output:

```
File URI: file:///home/akuli/mystbug/sansio-lsp-client/playground.py
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/akuli/mystbug/sansio-lsp-client/sansio_lsp_client/__main__.py", line 103, in <module>
    main()
  File "/home/akuli/mystbug/sansio-lsp-client/sansio_lsp_client/__main__.py", line 43, in main
    events = list(client.recv(data))
  File "/home/akuli/mystbug/sansio-lsp-client/sansio_lsp_client/client.py", line 109, in recv
    messages = list(_parse_messages(self._recv_buf))
  File "/home/akuli/mystbug/sansio-lsp-client/sansio_lsp_client/io_handler.py", line 95, in _parse_messages
    assert set(headers.keys()) == {"Content-Type", "Content-Length"}
AssertionError
```

For a very quick and dirty fix, I tried adding this line before the failing assert:

```python3
if 'Content-Type' not in headers: headers['Content-Type'] = 'application/vscode-jsonrpc; charset=utf8'
```

Then it failed with this output in Python:

```
File URI: file:///home/akuli/mystbug/sansio-lsp-client/playground.js
Initialized!
Server capabilities:
{'codeActionProvider': True,
 'completionProvider': {'resolveProvider': True, 'triggerCharacters': ['.']},
 'definitionProvider': True,
 'documentSymbolProvider': True,
 'executeCommandProvider': {'commands': []},
 'hoverProvider': True,
 'referencesProvider': True,
 'renameProvider': True,
 'signatureHelpProvider': {'triggerCharacters': ['(', ',']},
 'textDocumentSync': 1,
 'typeDefinitionProvider': True,
 'workspaceSymbolProvider': True,
 'xdefinitionProvider': True,
 'xdependenciesProvider': True,
 'xpackagesProvider': True,
 'xworkspaceReferencesProvider': True}
{'code': -32001,
 'data': {},
 'message': "Cannot read property 'ensureReferencedFiles' of undefined"}
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/akuli/mystbug/sansio-lsp-client/sansio_lsp_client/__main__.py", line 103, in <module>
    main()
  File "/home/akuli/mystbug/sansio-lsp-client/sansio_lsp_client/__main__.py", line 43, in main
    events = list(client.recv(data))
  File "/home/akuli/mystbug/sansio-lsp-client/sansio_lsp_client/client.py", line 124, in recv
    raise RuntimeError("Response error!")
RuntimeError: Response error!
```

and this output in node:

```
DEBUG Spawning 2 workers
DEBUG Worker 1 (PID 27753) online
DEBUG Worker 2 (PID 27754) online
INFO  Listening for incoming LSP connections on 2089
INFO  Listening for incoming LSP connections on 2089
DEBUG Connection 1 accepted
ERROR Handler for textDocument/completion failed: TypeError: Cannot read property 'ensureReferencedFiles' of undefined
    at TypeScriptService.textDocumentCompletion (/home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/typescript-service.js:906:14)
    at Object.<anonymous> (/home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/connection.js:199:48)
    at Generator.next (<anonymous>)
    at /home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/connection.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/connection.js:3:12)
    at MessageEmitter.<anonymous> (/home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/connection.js:127:47)
    at MessageEmitter.emit (events.js:214:15)
    at StreamMessageReader.callback (/home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/connection.js:51:18)
    at StreamMessageReader.onData (/home/akuli/mystbug/sansio-lsp-client/node_modules/vscode-jsonrpc/lib/messageReader.js:183:18) 
Message: {
  jsonrpc: '2.0',
  method: 'textDocument/completion',
  params: {
    textDocument: {
      uri: 'file:///home/akuli/mystbug/sansio-lsp-client/playground.js'
    },
    position: { line: 5, character: 12 },
    triggerKind: 1,
    triggerCharacter: null
  },
  id: 1
}
ERROR Handle textDocumentDidOpen: TypeError: Cannot read property 'ensureReferencedFiles' of undefined
    at TypeScriptService.<anonymous> (/home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/typescript-service.js:1202:39)
    at Generator.next (<anonymous>)
    at /home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/typescript-service.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/typescript-service.js:3:12)
    at TypeScriptService.textDocumentDidOpen (/home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/typescript-service.js:1199:16)
    at Object.<anonymous> (/home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/connection.js:199:48)
    at Generator.next (<anonymous>)
    at /home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/connection.js:7:71
    at new Promise (<anonymous>)
ERROR Stream was closed without shutdown notification
TypeError: Cannot read property 'dispose' of undefined
    at TypeScriptService.shutdown (/home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/typescript-service.js:212:29)
    at MessageEmitter.<anonymous> (/home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/connection.js:285:21)
    at MessageEmitter.emit (events.js:209:13)
    at /home/akuli/mystbug/sansio-lsp-client/node_modules/javascript-typescript-langserver/lib/connection.js:57:18
    at CallbackList.invoke (/home/akuli/mystbug/sansio-lsp-client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/akuli/mystbug/sansio-lsp-client/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at StreamMessageReader.fireClose (/home/akuli/mystbug/sansio-lsp-client/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/home/akuli/mystbug/sansio-lsp-client/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (events.js:214:15)
    at TCP.<anonymous> (net.js:588:12)
```

I don't know whether this is a sansio-lsp-client bug or javascript-typescript-langserver bug, but I think javascript-typescript-langserver shouldn't be quite this broken.

Versions:
```
$ python3 --version
Python 3.7.3
$ git rev-parse HEAD
b9e01a0f6be1b196f8613ace0d90fe36a3ed87aa
$ node --version
v12.9.1
$ npm --version
6.10.2
```

**Comment by PurpleMyst** [comment]
Searching for the exact error message on Google yields this GitHub issue https://github.com/sourcegraph/javascript-typescript-langserver/issues/372

It seems that this issue stems from a missing `rootUri` in the initialize request. Currently `Client.__init__` has it as an "optional" parameter, and the spec says that it's optional. It's probably best to set it though (in an editor) if some langservers don't work without it.

What do you think we should do?

**Comment by PurpleMyst** [comment]
Also I think I should add logging to this crate. Maybe I could finally use `structlog`, it seems so interesting..

**Comment by Akuli** [comment]
Maybe I should just set `rootUri` to wherever the first `.editorconfig` file or `.git` directory is found?

**Comment by PurpleMyst** [comment]
Does porcupine have no concept of an open folder? (a la VS code)

**Comment by Akuli** [comment]
There is no concept of an open folder, really only open files. I wrote some code to look for `editorconfig`, `.git` or README for now.

Let's keep this issue open for now. I'll let you know whether I get this to work or not.

**Comment by PurpleMyst** [comment]
Alright, let me know. I think `rust-analyzer` also needs a `rootUri`.

**Comment by PurpleMyst** [comment]
The headers thing is also weird..

**Comment by Akuli** [comment]
Seems like the header thing also affects clangd

**Comment by Akuli** [comment]
header thing fixed in #8

**Comment by PurpleMyst** [comment]
can we close this?

**Comment by Akuli** [comment]
I haven't used javascript-typescript-langserver in a long time. I'll reopen this or make a new issue if I want to later use it and it doesn't work.
